### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by rivers-fighting** [tnfe/tntweb-admin#11]
检出的最新代码，未改动代码，然后运行
E:\大前端\react\concent\github\tntweb-admin>tyarn run app
yarn run v1.22.11
$ cross-env node scripts/start.js
[HPM] Proxy created: /api/product/*  -> http://localhost:7777/
[HPM] Proxy created: /api/stock/*  -> http://localhost:7777/
[HPM] Proxy created: /api/*  -> http://localhost:3001/
i ｢wds｣: Project is running at http://172.27.229.20/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from E:\大前端\react\concent\github\tntweb-admin\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Failed to compile.

E:/大前端/react/concent/github/tntweb-admin/src/pages/AStepForm/model/reducer.ts
TypeScript error in E:/大前端/react/concent/github/tntweb-admin/src/pages/AStepForm/model/reducer.ts(82,22):
Object is of type 'unknown'.  TS2571

    80 |     return { appDetail, checkAppIdBtnLoading: false };
    81 |   } catch (err) {
  > 82 |     msgService.error(err.message);
       |                      ^
    83 |     return { checkAppIdBtnLoading: false };
    84 |   }
    85 | }

**Comment by fantasticsoul** [comment]
err 标注类型 any即可，最新版本ts对err类型要求更严了，这里我调整下
